kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: oso-local-test-cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"