apiVersion: v1
kind: Namespace
metadata:
  name: local-hive-metastore
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: local
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: getindata-hms
  namespace: local-hive-metastore
spec:
  interval: 5m
  url: https://getindata.github.io/hive-metastore
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hive-metastore
  namespace: local-hive-metastore
spec:
  chart:
    spec:
      chart: hive-metastore
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: getindata-hms
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    postgres:
      host: "hive-psql-postgresql.local-hive-psql.svc.cluster.local"
      port: 5432
      db: postgres
      username: postgres
      password: password
