apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  values:
    secretTargets:
      enabled: true
      authorizedSecrets:
        - operator-ca-tls-secret

