apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common/cert-manager.yaml
patches:
  - path: ./cert-manager-custom-helm-values.yaml
    target:
      kind: HelmRelease
    options:
      allowNameChange: true