---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-internal-cloudflare
  labels:
    toolkit.fluxcd.io/tenant: ops
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-internal-cloudflare
  namespace: ingress-internal-cloudflare
spec:
  interval: 24h
  url: https://helm.strrl.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-internal-cloudflare
  namespace: ingress-internal-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-internal-cloudflare
        namespace: ingress-internal-cloudflare
      interval: 12h
  values:
    cloudflare:
      apiToken: gcp:secretmanager:cloudflare-api-token/versions/1
      accountId: gcp:secretmanager:cloudflare-account-id/versions/1
      tunnelName: gcp:secretmanager:cloudflare-internal-tunnel-name/versions/1
