name: 'opensource_observer'
version: '0.2.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'opensource_observer'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]
log-path: dbt/logs
target-path: dbt/target

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  opensource_observer:
    +materialized: view
    marts:
      +materialized: table
