packages:
  - "warehouse/cloudquery-oss-directory"
  - "warehouse/cloudquery-github-resolve-repos"
  - "apps/docs"
  - "apps/frontend"
  - "apps/hasura"
  - "lib/oss-artifact-validators"
  - "ops/external-prs"
  - "ops/github-app-utils"
