[tool.poetry]
name = "oso"
version = "1.0.0"
description = "Impact measurement for open source software"
authors = ["Kariba Labs"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "bq2cloudsql", from = "warehouse/" },
    { include = "common", from = "warehouse/" },
    { include = "oso_dagster", from = "warehouse/" },
]

[tool.poetry.dependencies]
python = "^3.11,<3.13"
google-cloud-bigquery = "^3.17.1"
pendulum = "^3.0.0"
google-api-python-client = "^2.116.0"
cloud-sql-python-connector = { extras = ["pg8000"], version = "^1.6.0" }
sqlalchemy = "^2.0.25"
google-cloud-storage = "^2.14.0"
python-dotenv = "^1.0.1"
dbt-bigquery = "^1.7.0"
dbt-core = "^1.8.2"
textual = "^0.52.1"
google-cloud-service-management = "^1.8.3"
google-cloud-resource-manager = "^1.12.3"
google-cloud-service-usage = "^1.10.3"
boltons = "^23.1.1"
ruamel-yaml = "^0.18.6"
dagster = "^1.7.2"
dagster-dbt = "^0.23.2"
dagster-webserver = "^1.7.2"
dagster-gcp = "^0.23.2"
duckdb = "^0.10.2"
dask-kubernetes = "^2024.4.2"
dask = { extras = ["distributed"], version = "^2024.4.2" }
lz4 = "^4.3.3"
arrow = "^1.3.0"
polars = "^0.20.23"
requests = "^2.31.0"
dagster-postgres = "^0.23.6"
pytest = "^8.2.1"


[tool.poetry.scripts]
bq2cloudsql = 'bq2cloudsql.script:run'
oso_lets_go = 'oso_lets_go.wizard:run'

[tool.poetry.group.dev.dependencies]
ipython = "^8.21.0"
sqlfluff = "^3.0.7"
sqlfluff-templater-dbt = "^3.0.7"
shandy-sqlfmt = { extras = ["jinjafmt"], version = "^0.21.1" }
dagster-webserver = "^1.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.sqlfluff]
max_line_length = 80

[tool.sqlfluff.core]
templater = "dbt"

[tool.sqlfluff.indentation]
indent_unit = "space"
tab_space_size = 2

[tool.sqlfluff.templater.jinja]
load_macros_from_path = "warehouse/dbt/macros/"
apply_dbt_builtins = true
library_path = "warehouse/common/dbtlintmock"

[tool.sqlfluff.templater.dbt]
project_dir = "."
target = "playground"

[tool.dagster]
module_name = "oso_dagster.definitions"
