[tool.poetry]
name = "oso"
version = "1.0.0"
description = "Impact measurement for open source software"
authors = ["Kariba Labs"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "bq2cloudsql", from = "warehouse/" },
    { include = "common", from = "warehouse/" },
    { include = "oso_dagster", from = "warehouse/" },
]

[tool.poetry.dependencies]
python = "^3.12,<3.13"
arrow = "^1.3.0"
boltons = "^23.1.1"
click = "^8.1.7"
cloud-sql-python-connector = { extras = ["pg8000"], version = "^1.6.0" }
dagster = "^1.7.2"
dagster-dbt = "^0.23.2"
dagster-gcp = "^0.23.2"
dagster-polars = "^0.23.10"
dagster-postgres = "^0.23.6"
dagster-webserver = "^1.7.2"
dask = { extras = ["distributed"], version = "^2024.4.2" }
dask-kubernetes = "^2024.4.2"
dbt-bigquery = "^1.7.0"
dbt-core = "^1.8.2"
duckdb = "^0.10.2"
google-api-python-client = "^2.116.0"
google-cloud-bigquery = "^3.17.1"
google-cloud-bigquery-datatransfer = "^3.15.3"
google-cloud-resource-manager = "^1.12.3"
google-cloud-service-management = "^1.8.3"
google-cloud-service-usage = "^1.10.3"
google-cloud-storage = "^2.14.0"
lz4 = "^4.3.3"
oss-directory = "^0.2.0"
pendulum = "^3.0.0"
polars = "^0.20.23"
pytest = "^8.2.1"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
ruamel-yaml = "^0.18.6"
ruff = "^0.4.10"
sqlalchemy = "^2.0.25"
textual = "^0.52.1"
dagster-polars = "^0.23.10"
click = "^8.1.7"
oss-directory = "^0.2.0"
dagster-embedded-elt = "^0.23.11"
google-cloud-secret-manager = "^2.20.0"
dlt = {extras = ["filesystem"], version = "^0.4.12"}
gcsfs = "^2024.6.1"


[tool.poetry.scripts]
bq2cloudsql = 'bq2cloudsql.script:run'
oso_lets_go = 'oso_lets_go.wizard:run'

[tool.poetry.group.dev.dependencies]
dagster-webserver = "^1.7.2"
ipython = "^8.21.0"
shandy-sqlfmt = { extras = ["jinjafmt"], version = "^0.21.1" }
sqlfluff = "^3.0.7"
sqlfluff-templater-dbt = "^3.0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.sqlfluff]
max_line_length = 80

[tool.sqlfluff.core]
templater = "dbt"

[tool.sqlfluff.indentation]
indent_unit = "space"
tab_space_size = 2

[tool.sqlfluff.templater.jinja]
load_macros_from_path = "warehouse/dbt/macros/"
apply_dbt_builtins = true
library_path = "warehouse/common/dbtlintmock"

[tool.sqlfluff.templater.dbt]
project_dir = "."
target = "playground"

[tool.dagster]
module_name = "oso_dagster.definitions"

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "standard"
ignore = [
    "warehouse/cloudquery-example-plugin",
    "warehouse/cloudquery-dune-contract-usage",
    "warehouse/bq2cloudsql",
    "warehouse/meltano-setup",
    "warehouse/oso_lets_go",
    "warehouse/oso_dagster/dlt_sources",
]

[tool.ruff]
exclude = [
    "warehouse/cloudquery-example-plugin",
    "warehouse/cloudquery-dune-contract-usage",
    "warehouse/bq2cloudsql",
    "warehouse/meltano-setup",
    "warehouse/oso_lets_go",
    "warehouse/oso_dagster/dlt_sources",
    "warehouse/oso_dagster/dlt_sources/**/*.py",
    "warehouse/oso_dagster/dlt_sources/*.py",
]

[tool.ruff.lint]
exclude = [
    "warehouse/oso_dagster/dlt_sources/**/*.py",
    "warehouse/oso_dagster/dlt_sources/*.py",
]
