apiVersion: v1
kind: Namespace
metadata:
  name: base-trino
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trino
  namespace: base-trino
spec:
  interval: 5m
  url: https://trinodb.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trino
  namespace: base-trino
spec:
  chart:
    spec:
      chart: trino
      version: "0.33.0"
      sourceRef:
        kind: HelmRepository
        name: trino
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    additionalConfigProperties:
      - retry-policy=QUERY
    additionalExchangeManagerProperties:
      - "exchange.sink-buffers-per-partition=6"
      - "exchange.sink-buffer-pool-min-size=6"
      - "exchange.source-concurrent-readers=6"
      - "exchange.s3.region=us"
      - "exchange.s3.aws-access-key=${ENV:TRINO_GCS_KEY_ID}"
      - "exchange.s3.aws-secret-key=${ENV:TRINO_GCS_SECRET}"
      - "exchange.s3.endpoint=https://storage.googleapis.com"
    serviceAccount:
      create: true
      name: base-trino
    coordinator:
      additionalVolumes:
        - name: cache
          emptyDir: {}
      additionalVolumeMounts:
        - name: cache
          mountPath: /metrics-cache
      jvm:
        maxHeapSize: "17G"
      additionalJVMConfig:
        - "--add-opens=java.base/java.nio=ALL-UNNAMED"
      
    worker:
      additionalVolumes:
        - name: cache
          emptyDir: {}
      additionalVolumeMounts:
        - name: cache
          mountPath: /metrics-cache

      config:
        query:
          maxMemoryPerNode: 140GB
      jvm:
        maxHeapSize: "350G"
      additionalJVMConfig:
        - "--add-opens=java.base/java.nio=ALL-UNNAMED"

    server:
      exchangeManager:
        name: filesystem
        baseDir: gs://oso-dataset-transfer-bucket/trino-exchange/
      config:
        query:
          maxMemory: "1400GB"
      workers: 1
      autoscaling:
        enabled: true
        maxReplicas: 9
        targetCPUUtilizationPercentage: 20
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
            - type: Pods
              value: 1
              periodSeconds: 60
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 4
              periodSeconds: 15
            selectPolicy: Max
    catalogs:
      metrics: |
        connector.name=iceberg
        iceberg.catalog.type=hive_metastore
        hive.metastore.uri=thrift://10.145.192.27:9083
        hive.metastore-cache-ttl=0s
        hive.metastore-refresh-interval=5s
        hive.metastore.thrift.client.connect-timeout=10s
        hive.metastore.thrift.client.read-timeout=10s
        iceberg.use-file-size-from-metadata=false
        fs.native-gcs.enabled=true
        fs.cache.enabled=true
        fs.cache.max-sizes=300GB
        fs.cache.directories=/metrics-cache
        gcs.project-id=opensource-observer
        iceberg.max-partitions-per-writer=1000
      source: |
        connector.name=hive
        hive.metastore.uri=thrift://10.145.192.27:9083
        fs.native-gcs.enabled=true
        gcs.project-id=opensource-observer
        hive.non-managed-table-writes-enabled=true
      bigquery: |
        connector.name=bigquery
        bigquery.project-id=opensource-observer
