# Intentionally the password is admin as this is for local testing.
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: local-minio
type: Opaque
data:
  accesskey: YWRtaW4= # admin
  secretkey: YWRtaW4=
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: local-minio
spec:
  credsSecret:
    name: minio-secret
  image: minio/minio:RELEASE.2024-11-07T00-52-20Z
  imagePullPolicy: IfNotPresent
  pools:
  - name: pool-0
    servers: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
        storageClassName: standard
    volumesPerServer: 1
  requestAutoCert: false
  users:
  - name: storage-user-0