gateways:
  local:
    connection:
      type: duckdb
      database: /data/int_events/test.db

default_gateway: local

variables:
  fulltime_dev_days: 10
  activity_window: 30

model_defaults:
  dialect: duckdb
  start: 2024-08-19
