---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-cloudflare-tunnel
  labels:
    toolkit.fluxcd.io/tenant: ops
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-cloudflare-tunnel
  namespace: ingress-cloudflare-tunnel
spec:
  interval: 24h
  url: https://helm.strrl.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-cloudflare-tunnel
  namespace: ingress-cloudflare-tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-cloudflare-tunnel
        namespace: ingress-cloudflare-tunnel
      interval: 12h
  values:
    cloudflare:
      apiToken: ""
