apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-cloudsql-proxy
spec:
  values:
    cloudsql:
      instances:
        - instance: oso-psql
          region: us-central1
          project: opensource-observer
          port: 5432