apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-trino
spec:
  values:
    serviceAccount:
      name: local-trino
    worker:
      jvm:
        maxHeapSize: 2G
      config:
        query:
          maxMemoryPerNode: 500MB 
    coordinator:
      jvm:
        maxHeapSize: 2G
      config:
        query:
          maxMemoryPerNode: 500MB 
    catalogs:
      metrics: |
        connector.name=postgresql
        connection-url=jdbc:postgresql://trino-psql-postgresql.local-trino-psql.svc.cluster.local:5432/postgres
        connection-user=postgres
        connection-password=password
      source: |
        connector.name=hive
        hive.metastore.uri=thrift://hive-metastore.local-hive-metastore.svc.cluster.local:9083
        hive.non-managed-table-writes-enabled=true
        fs.native-s3.enabled=true
        s3.path-style-access=true
        s3.endpoint=https://minio.local-minio.svc.cluster.local
        s3.aws-access-key=storage-user
        s3.aws-secret-key=password
      bigquery: |
        connector.name=postgresql
        connection-url=jdbc:postgresql://trino-psql-postgresql.local-trino-psql.svc.cluster.local:5432/postgres
        connection-user=postgres
        connection-password=password