apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
spec:
  values:
    global:
      serviceAccountName: production-dagster
    configMap:
      secretPrefix: "gcp:secretmanager:production-dagster"
    dagster:
      global: 
        serviceAccountName: production-dagster
      ingress:
        enabled: true
        ingressClassName: ingress-internal-cloudflare
        dagsterWebserver:
          host: admin-dagster.opensource.observer
        readOnlyDagsterWebserver:
          host: readonly-dagster.opensource.observer
      