apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dagster
  - ./cloudsql-proxy
  - ./redis
  # Uncomment to turn on trino
  - ./trino
  #- ./metrics-calculation-service
