apiVersion: v1
kind: Namespace
metadata:
  name: base-dagster
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
  namespace: base-dagster
spec:
  chart:
    spec:
      chart: ./ops/helm-charts/oso-dagster
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    global:
      serviceAccountName: base-dagster
    dagster:
      nameOverride: "dagster"
      ingress:
        enabled: true
        ingressClassName: ingress-internal-cloudflare
        dagsterWebserver:
          host: base-admin-dagster.opensource.observer
        readOnlyDagsterWebserver:
          host: base-readonly-dagster.opensource.observer
      runLauncher:
        config:
          k8sRunLauncher:
            envConfigMaps:
              - name: dagster-oso-extra-env
            # runK8sConfig:
            #   podSpecConfig:
            #     tolerations:
            #       - key: pool_type
            #         effect: NoSchedule
            #         operator: Equal
            #         value: spot
            #     nodeSelector:
            #       pool_type: spot
      dagsterWebserver:
        envConfigMaps:
          - name: dagster-oso-extra-env
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      dagsterDaemon:
        envConfigMaps:
          - name: dagster-oso-extra-env
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
  postRenderers:
    - kustomize:
        patches:
          - patch: | 
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: all-deployments
              spec:
                template:
                  spec:
                    initContainers:
                      - name: check-db-ready
                        envFrom:
                          - configMapRef:
                              name: dagster-oso-extra-env
            target:
              kind: Deployment
              labelSelector: app.kubernetes.io/name=dagster
