name: 'OP Collective'
description: A request related to Optimism datasets or Retro Funding metrics
title: 'OP: '
body:
  - type: textarea
    attributes:
      label: What would you like to see? Please provide a clear and concise description of what you want
      description: 'Examples: Propose some ideas for impact metrics related to interop; Create a new collection for Rust packages; Organize a data challenge to rank OP stack dependencies by network importance.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any additional context you can share? Feel free to include notes or screenshots that can help us research and track the issue.
      description: 'Examples: Summary of notes from a recent community call; Screenshot of a Telegram chat with badgeholders.'
    validations:
      required: false
  - type: input
    attributes:
      label: Is there a write-up or doc associated with this issue? Please link to it.
      description: 'Example: https://www.notion.so/templates/product-spec'
    validations:
      required: false
