name: 'Retro Funding'
description: A community-submitted issue related to Optimism Retro Funding
title: 'RF: '
assignees: ccerv1
labels: []
body:
  - type: textarea
    attributes:
      label: What would you like to see?
      description: 'A clear and concise description of what you're looking for. Examples: Propose some ideas for impact metrics related to interop; Create a new collection for RF5 projects; Organize a data challenge to rank OP stack dependencies by network importance.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: 'Any added context or screenshots that might be helpful for us to research and track the issue.'
    validations:
      required: false
  - type: input
    attributes:
      label: Is there a write-up or doc associated with this issue? Please link to it.
      description: 'Example: https://www.notion.so/templates/product-spec'
    validations:
      required: false
