apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-oso-extra-env
data:
  DAGSTER_PG_USER: "{{ .Values.configMap.secretPrefix }}-{{ .Values.secretmanagerKeys.dbUser }}"
  DAGSTER_PG_DB_NAME: "{{ .Values.configMap.secretPrefix }}-{{ .Values.secretmanagerKeys.dbName }}"
  DAGSTER_DBT_IMPERSONATE_SERVICE_ACCOUNT: "{{ .Values.configMap.secretPrefix }}-{{ .Values.secretmanagerKeys.impersonateServiceAccount }}"
  DAGSTER_PG_PORT: "{{ .Values.pg.port }}"
  DAGSTER_PG_HOST: "{{ .Values.pg.host }}"
  DAGSTER_USE_LOCAL_SECRETS: "False"
  DAGSTER_GCP_SECRETS_PREFIX: "{{ .Values.global.serviceAccountName }}"
  DAGSTER_STAGING_BUCKET_URL: "{{ .Values.configMap.secretPrefix }}-{{ .Values.secretmanagerKeys.stagingBucketUrl }}"
  DAGSTER_DISCORD_WEBHOOK_URL: "{{ .Values.configMap.secretPrefix }}-{{ .Values.secretmanagerKeys.discordWebhookUrl }}"
  DAGSTER_ALERTS_BASE_URL: "{{ .Values.alerts.baseUrl }}"
  DAGSTER_HTTP_CACHE: "{{ .Values.cache.uri }}"