apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-scaler-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.dagster.global.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: dagster-scaler-role
  apiGroup: rbac.authorization.k8s.io
