---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
    - name: certificates
    - name: operators
  interval: 1h
  retryInterval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./ops/k8s-apps/local
  force: true
  prune: true
  wait: true