version: '3'

volumes:
  node_modules:
  indexer_modules:
  indexer_dist:
  frontend_modules:
  pnpm_home:
  pnpm_store:


services:
  install:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    command: bash docker/install.sh
    volumes:
      - ../:/usr/src/app
      - pnpm_store:/usr/src/app/.pnpm_store
      - pnpm_store:/usr/src/app/.pnpm-store
      - node_modules:/usr/src/app/node_modules
      - indexer_modules:/usr/src/app/indexer/node_modules
      - indexer_dist:/usr/src/app/indexer/dist
      - frontend_modules:/usr/src/app/frontend/node_modules
      - pnpm_home:/pnpm
    environment:
      - PNPM_HOME=/pnpm
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test:
    profiles:
      - testing
    privileged: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    command: bash docker/test.sh
    depends_on:
      install:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      - PNPM_HOME=/pnpm
      - DB_HOST=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - TEST_ONLY_ALLOW_CLEAR_DB=true
    volumes:
      - ../:/usr/src/app
      - pnpm_store:/usr/src/app/.pnpm_store
      - pnpm_store:/usr/src/app/.pnpm-store
      - node_modules:/usr/src/app/node_modules
      - indexer_modules:/usr/src/app/indexer/node_modules
      - indexer_dist:/usr/src/app/indexer/dist
      - frontend_modules:/usr/src/app/frontend/node_modules
      - pnpm_home:/pnpm
