version: '3'

volumes:
  node_modules:
  indexer_modules:
  indexer_dist:
  frontend_modules:
  frontend_next:
  pnpm_home:
  pnpm_store:


services:
  install:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    command: bash docker/install.sh
    volumes:
      - ../:/usr/src/app
      - pnpm_store:/usr/src/app/.pnpm_store
      - pnpm_store:/usr/src/app/.pnpm-store
      - node_modules:/usr/src/app/node_modules
      - indexer_modules:/usr/src/app/indexer/node_modules
      - indexer_dist:/usr/src/app/indexer/dist
      - frontend_next:/usr/src/app/frontend/.next
      - frontend_modules:/usr/src/app/frontend/node_modules
      - pnpm_home:/pnpm
    environment:
      - PNPM_HOME=/pnpm
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - TEST_ONLY_ALLOW_CLEAR_DB=true
      - X_GITHUB_GRAPHQL_API=test
      - X_GITHUB_TOKEN=test
      - DUNE_API_KEY=test
      - PLASMIC_PROJECT_ID
      - PLASMIC_PROJECT_API_TOKEN
      - NEXT_PUBLIC_DOMAIN
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test:
    profiles:
      - testing
    privileged: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    command: bash docker/test.sh
    depends_on:
      install:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - PNPM_HOME=/pnpm
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - TEST_ONLY_ALLOW_CLEAR_DB=true
      - ENABLE_DB_TESTS=true
      - ENABLE_REDIS=true
      - X_GITHUB_GRAPHQL_API=test
      - X_GITHUB_TOKEN=test
      - DUNE_API_KEY=test
    volumes:
      - ../:/usr/src/app
      - pnpm_store:/usr/src/app/.pnpm_store
      - pnpm_store:/usr/src/app/.pnpm-store
      - node_modules:/usr/src/app/node_modules
      - indexer_modules:/usr/src/app/indexer/node_modules
      - indexer_dist:/usr/src/app/indexer/dist
      - frontend_next:/usr/src/app/frontend/.next
      - frontend_modules:/usr/src/app/frontend/node_modules
      - pnpm_home:/pnpm
