apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-dagster
spec:
  values:
    pg:
      host: production-cloudsql-proxy-gcloud-sqlproxy.production-cloudsql-proxy.svc.cluster.local
      port: "5432"
    global:
      serviceAccountName: production-dagster
    configMap:
      secretPrefix: "gcp:secretmanager:production-dagster"
    alerts:
      baseUrl: "https://dagster.opensource.observer"
    cache:
      uri: "redis://redis.production-redis.svc.cluster.local:6379?ttl=3600"
    dagster:
      global: 
        serviceAccountName: production-dagster
      ingress:
        enabled: true
        ingressClassName: ingress-internal-cloudflare
        dagsterWebserver:
          host: admin-dagster.opensource.observer
        readOnlyDagsterWebserver:
          host: dagster.opensource.observer
      