---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tailscale-operator-oauth-secret
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/opensource-observer/secrets/production-tailscale-client-id/versions/latest"
        path: "client_id"
      - resourceName: "projects/opensource-observer/secrets/production-tailscale-client-secret/versions/latest"
        path: "client_secret"