apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-trino
spec:
  values:
    env:
      - name: TRINO_GCS_KEY_ID
        value: gcp:secretmanager:production-mcs-gcs-key-id/versions/latest
      - name: TRINO_GCS_SECRET
        value: gcp:secretmanager:production-mcs-gcs-secret/versions/latest
    serviceAccount:
      name: production-trino
    coordinator:
      resources:
        requests:
          cpu: 7500m
          memory: 46000Mi
      tolerations:
        - key: pool_type
          operator: Equal
          value: trino-coordinator
          effect: NoSchedule
      nodeSelector:
        pool_type: trino-coordinator
    worker:
      resources:
        requests:
          cpu: 63000m
          memory: 390000Mi
      tolerations:
        - key: pool_type
          operator: Equal
          value: trino-worker
          effect: NoSchedule
      nodeSelector:
        pool_type: trino-worker