apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common/cert-manager.yaml
- ../common/self-signed-certs.yaml
- kube-secrets-init.yaml
- ingress-internal-cloudflare.yaml
- cloudsql-proxy-operator.yaml
