apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
patchesJson6902:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
    patch: |-
      - op: replace
        path: /metadata/name
        value: staging-podinfo

  - target:
      kind: Namespace
      version: v1
    patch: |-
      - op: replace
        path: /metadata/name
        value: staging-podinfo
      
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /metadata/name
        value: staging-podinfo
      
      - op: replace
        path: /spec/chart/sourceRef/name
        value: staging-podinfo