---
apiVersion: v1
kind: Secret
metadata:
  name: nessie-postgres
  namespace: local-nessie
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 encoded value of 'admin'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
---
apiVersion: v1
kind: Secret
metadata:
  name: nessie-minio
  namespace: local-nessie
type: Opaque
data:
  accessKey: YWRtaW4=  # base64 encoded value of 'admin'
  secretKey: cGFzc3dvcmQ=  # base64 encoded value of 'password'