apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-mcs
spec:
  values:
    mcs:
      cluster:
        name: mcs-worker
        namespace: production-mcs
        image:
          repo: "ghcr.io/opensource-observer/oso"
          tag: "latest"
        scheduler:
          memory:
            limit: "23Gi"
            request: "20Gi"
          poolType: "mcs-scheduler"
        worker:
          threads: "16"
          memory:
            limit: "96Gi"
            request: "90Gi"
          poolType: "mcs-worker"
          duckdb_path: "/scratch/mcs-local.db"
      trino:
        host: production-trino-trino.production-trino.svc.cluster.local
        port: 8080
        user: sqlmesh
      gcs:
        bucket: oso-dataset-transfer-bucket
        key_id: gcp:secretmanager:production-mcs-gcs-key-id/versions/latest
        secret: gcp:secretmanager:production-mcs-gcs-secret/versions/latest