---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-operator
  labels:
    toolkit.fluxcd.io/tenant: ops
    opensource.observer/cert-inject: "enabled"
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: tailscale-operator
      interval: 1h