# Default values for oso-dagster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dagster:
  global:
    serviceAccountName: "staging-dagster"
  postgresql:
    enabled: false
    postgresqlPassword: "gcp:secretmanager:dagster-db-password/versions/1"
  dagsterWebserver:
    enableReadOnly: true

global:
  dagsterInternalName: "dagster"

configMap:
  name: "dagster-extra-env-config-map"
  secretPrefix: "gcp:secretmanager:dagster"
secretmanagerKeys: 
  dbUser: "db-user/versions/latest"
  dbHost: "db-host/versions/latest"
  dbPort: "db-port/versions/latest"
  dbName: "db-name/versions/latest"
  impersonateServiceAccount: "dbt-impersonate-service-account/versions/latest"
  stagingBucketUrl: "staging-bucket-url/versions/latest"
  discordWebhookUrl: "discord-webhook-url/versions/latest"
pg:
  port: "5432"
  host: "127.0.0.1"
alerts:
  baseUrl: ""