kind: source
spec:
  name: github-resolve-repos
  name: "github-resolve-repos"
  registry: "grpc"
  path: "localhost:7777"
  version: "v0.0.1"
  # path: "ghcr.io/opensource-observer/cloudquery-github-resolve-repos:${DOCKER_TAG}"
  # registry: "docker"
  # version: "v0.0.1"
  tables:
    ["*"]
  destinations:
    - "bigquery"
  spec:
    projects_input_path: "${CLOUDQUERY_FILE_DIRECTORY}/projects.json"
    token: ${GITHUB_TOKEN}
---
kind: destination
spec:
  name: bigquery
  path: cloudquery/bigquery
  registry: cloudquery
  version: "v3.3.13"
  write_mode: "append"
  spec:
    project_id: oso-production
    dataset_id: opensource_observer
