# Generic worker executor. This is callable for use with cron scheduling.

# Execute the worker for a specific group
name: external-pr-test-deploy

inputs:
  sha:
    description: 'The sha to deploy'
    required: true
  pr:
    description: The pr number
    required: true
  requester:
    description: The user requesting the deploy
    required: true
  author:
    description: The author of the pull
    required: true

runs:
  using: "composite"
  steps:
    - name: Set pr and sha in the environment
      shell: bash
      run: |
        echo "PR_TOOLS_PR=${{ inputs.pr }}" >> "$GITHUB_ENV"
        echo "PR_TOOLS_SHA=${{ inputs.sha }}" >> "$GITHUB_ENV"

    # TODO: We should only deploy when data warehouse related files have changed. 
    # - name: Get changed files and write the outputs to a JSON file
    #   id: changed-files-write-output-files-json
    #   uses: tj-actions/changed-files@v43
    #   with:
    #     json: true
    #     write_output_files: true

    # - name: Evaluate if this is eligible for deployment
    #   id: is_eligible
    #   run: |
    #     cd ops/external-prs && pnpm tools test-deploy is-eligible $GITHUB_OUTPUT

    