---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcs.fullname" . }}
spec:
  selector:
    {{ include "mcs.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.mcs.service.port }}
      targetPort: 8000