# This is a test meltano pipeline
name: external-prs-handle-comment

on:
  issue_comment:
    types: 
      - created
      - edited

jobs:
  external-prs-handle-comment:
    name: external-prs-handle-commit
    environment: external-prs-app
    runs-on: ubuntu-latest

    # This job only runs for pull request comments
    if: github.event.issue.pull_request && contains(fromJson('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup external pr tools
        uses: ./.github/workflows/setup-external-pr-tools

      - run: |
          cd ops/external-prs && pnpm tools parse-comment ${{ github.repository }} ${{ github.event.comment.id }} sha.out
