# THIS IS A TEMPORARY CRON'D WORKER TO AUTOMATICALLY RUN GITHUB JOBS. EVENTUALLY
# THESE SHOULD BE SPAWNED INSIDE THE SCHEDULER FROM WITHIN NODE

# Execute the worker for a specific group
name: os-observer-indexer-worker-npm

# Trigger the workflow when:
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Schedule every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  collector-worker-call-npm:
    name: collector-worker-run-npm
    environment: indexer
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run the reusable workflow
        uses: ./.github/workflows/indexer-worker.yml
        with:
          group: npm
        