# Allow for manual queuing of jobs
name: os-observer-indexer-backfill
env:
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ vars.DB_DATABASE }}
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
  CACHE_DIR: /tmp/oso-cache

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      collector:
        description: 'the name of the collector'
        required: true
        type: choice
        options:
          - "npm-downloads"
          - "github-commits" 
          - "github-issues"
          - "github-followers"
          - "dune-daily-contract-usage"
          - "dune-funding-events"
          - "dependents"
      start-date:
        description: 'the start date for backfill'
        required: true
      end-date:
        description: 'the end date for backfill'
        required: false
      backfill-interval-days:
        description: 'how many days at a time do we backfill'
        required: true 
        default: '30'

jobs:
  collector-worker-run:
    name: collector-worker-run
    environment: indexer
    runs-on: ubuntu-latest

    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18.x"

      - name: Build
        run: pnpm build:indexer

      - name: Create a job with the given parameters
        run: bash .github/scripts/backfill.sh ${{ inputs.collector }} ${{ inputs.start-date }} ${{ inputs.backfill-interval-days }} ${{ inputs.end-date }}