name: os-observer-manual
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  PLASMIC_PROJECT_API_TOKEN: ${{ vars.PLASMIC_PROJECT_API_TOKEN }}
  PLASMIC_PROJECT_ID: ${{ vars.PLASMIC_PROJECT_ID }}

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: 'npmDownloads'
        type: choice
        options:
        - "npmDownloads"
        - "githubCommits" 
      args:
        description: 'Arguments to pass to the command'
        required: false
        default: ''
        type: string

jobs:
  fetch-data:
    # NOTE: This name appears in GitHub's Checks API.
    name: fetch-data
    environment: indexer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18.x"
      - name: Build
        run: pnpm build
      - name: Run
        run: pnpm start:indexer ${{ inputs.command }} ${{ inputs.args }}
