name: os-observer-indexer-clear-cache
env:
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ vars.DB_DATABASE }}
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
  CACHE_DIR: /tmp/oso-cache

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      group:
        description: 'the cache group to clear'
        required: true
        type: choice
        options:
          - "npm"
          - "dune" 
          - "github"

jobs:
  collector-worker-run:
    name: collector-worker-run
    environment: indexer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup environment
        shell: bash
        run: |
          echo "CACHE_PREFIX=${{ inputs.group }}" >> $GITHUB_ENV

      - name: Create empty cache dir
        run: |
          mkdir -p ${CACHE_DIR}

      - name: Clear cache
        run: bash .github/scripts/write-cache.sh