name: os-observer-autocrawl
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

# Trigger the workflow when:
on:
  workflow_dispatch:
  schedule:
    # Every day at 14:00 UTC = 07:00 PDT
    - cron: '0 14 * * *'

jobs:
  fetch-data:
    # NOTE: This name appears in GitHub's Checks API.
    name: fetch-data
    environment: indexer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18.x"
      - name: Run
        run: pnpm start:indexer runAutocrawl
