# THIS IS A TEMPORARY CRON'D WORKER TO AUTOMATICALLY RUN GITHUB JOBS. EVENTUALLY
# THESE SHOULD BE SPAWNED INSIDE THE SCHEDULER FROM WITHIN NODE

# Execute the worker for a specific group
name: os-observer-indexer-worker-dune

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Schedule every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  collector-worker-call-dune:
    uses: opensource-observer/oso/.github/workflows/indexer-worker.yml@main
    with:
      group: dune