# Allow for manual queuing of jobs
name: os-observer-indexer-refresh-mvs
env:
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ vars.DB_DATABASE }}
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
  DB_APPLICATION_NAME: indexer-create-job
  CACHE_DIR: /tmp/oso-cache

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      start-date:
        description: 'the start date for continous aggregates (ISO8601)'
        required: true
      end-date:
        description: 'the start date for continous aggregates (ISO8601)'
        required: true

jobs:
  collector-worker-run:
    name: collector-worker-run
    environment: indexer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18.x"

      - name: Build
        run: pnpm build:indexer

      - name: Refresh the materialized views
        run: pnpm start:indexer db-utils refresh-mvs --start-date ${{ inputs.start-date }} --end-date ${{ inputs.end-date }}