# We need to push credentials into github that have no actual permissions for
# anything. However, just in case those credentials expire every hour we do this
# by having a GCP project where service account keys expire every hour. This is
# done to allow for CI to run some jobs that need a GCP Service Account but 
# actually don't need access to run. This will allow us to use some checks with 
# contributors without write access to the repo

# This workflow will run every 30 mins to hopefully ensure that credentials
# don't expire even if this script errors.
name: warehouse-run-data-pipeline
env:
  BIGQUERY_DATASET_ID: ${{ vars.BIGQUERY_DATASET_ID }}

# For now this only runs on a schedule once a day. Once we have made some of the
# plugin workflows more incremental we will run this on _every_ commit to main
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:

    # Schedule every 30 mins
    - cron: '*/30 * * * *'

jobs:
  refresh-test-credentials:
    name: refresh-test-credentials
    environment: ops
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Authenticate to google with an ops user
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_OPS_CREDENTIALS_JSON }}'
          create_credentials_file: true

      - name: Setup external pr tools
        uses: ./.github/workflows/setup-external-pr-tools

      - name: Refresh credentials for the oso-test-dummy user on the testing environment
        shell: bash
        run: |
          gcloud iam service-account keys create dummy.json --iam-account=oso-test-dummy@oso-pull-requests.iam.gserviceaccount.com && 
          cat dummy.json | base64 -i - -o - | gh variable set --environment testing GOOGLE_TEST_DUMMY_CREDENTIALS_JSON 
      
      - name: Refresh credentials for the bigquery-admin user on the external-prs-app environment
        shell: bash
        run: |
          gcloud iam service-account keys create bigquery-admin.json --iam-account=oso-test-dummy@oso-pull-requests.iam.gserviceaccount.com && 
          cat bigquery-admin.json | base64 -i - -o - | gh variable set --environment external-prs-app GOOGLE_BIGQUERY_ADMIN_CREDENTIALS_JSON 