# This is a test meltano pipeline
name: test-meltano-pipeline
env:
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAP_POSTGRES_AIRBYTE_CONFIG_PASSWORD: ${{ secrets.DB_PASSWORD }}
  TAP_POSTGRES_AIRBYTE_CONFIG_HOST: ${{ secrets.DB_HOST }}
  TAP_POSTGRES_AIRBYTE_CONFIG_DATABASE: ${{ vars.DB_NAME }}
  TAP_POSTGRES_AIRBYTE_CONFIG_PORT: ${{ vars.DB_PORT }}
  TAP_POSTGRES_AIRBYTE_CONFIG_USERNAME: ${{ vars.DB_USERNAME }}

on:
  workflow_dispatch:

jobs:
  warehouse-run-data-pipeline:
    name: warehouse-run-data-pipeline
    environment: indexer
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.13' 
      
      - uses: snok/install-poetry@v1
        with:
          version: '1.7.1'

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual  
      
      - name: Run poetry install
        run: |
          cd warehouse/meltano-setup && poetry install

      - name: Run meltano
        run: |
          cd warehouse/meltano-setup 
          && poetry meltano install
          && poetry meltano run tap-postgres target-jsonl
      
      # At this time this auth isn't working for dbt
      # - uses: 'google-github-actions/auth@v2'
      #   with:
      #     service_account: oso-github-actions@oso-production.iam.gserviceaccount.com 
      #     workload_identity_provider: projects/1054148520225/locations/global/workloadIdentityPools/github/providers/oso-github-actions
      #     create_credentials_file: true
      #     access_token_lifetime: 3600s
