name: warehouse-publish-cloudquery-plugins
env:
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# This workflow only runs when a commit is completed on main. 
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main

jobs:
  warehouse-publish-cloudquery-plugins:
    name: warehouse-publish-cloudquery-plugins
    environment: indexer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear cache
        run: bash .github/scripts/package-cloudquery-plugins.sh