apiVersion: v1
kind: Namespace
metadata:
  name: local-hive-psql
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: local
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: local-hive-psql
spec:
  type: "oci"
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hive-psql
  namespace: local-hive-psql
spec:
  chart:
    spec:
      chart: postgresql
      version: "16.4.5"
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    auth:
      user: "postgres"
      postgresPassword: "password"

    passwordUpdateJob:
      enabled: true
